export const BACKGROUND_REFRESH_INTERVAL = 30;
export const CANVAS_REFRESH_INTERVAL = 30;

export const CANVAS_RADIUS = 400.0;
export const CANVAS_LENGTH = CANVAS_RADIUS * 2;
export const ROAD_RADIUS = 50.0;
export const ROAD_LENGTH = CANVAS_RADIUS - ROAD_RADIUS;

export const TRAFFIC_LIGHT_RADIUS = 4.0;
